version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres_scrapad
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      DATABASE_HOST: 127.0.0.1
      POSTGRES_DB: db_scrapad

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_scrapad
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: inaki.garcianoya@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres